-- 示例数据库 schema

-- magic-api 资源存储表
CREATE TABLE IF NOT EXISTS magic_api_file (
    file_path   VARCHAR(512)  NOT NULL,
    file_content TEXT,
    create_time BIGINT        DEFAULT 0,
    modify_time BIGINT        DEFAULT 0,
    PRIMARY KEY (file_path)
);

-- 业务表
CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    email   VARCHAR(200),
    age     INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    product     VARCHAR(200) NOT NULL,
    amount      DECIMAL(10,2) NOT NULL,
    status      VARCHAR(20) DEFAULT 'PENDING',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
