FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="MagicOps <dev@cywu.top>"

WORKDIR /app

COPY magicops-console/target/magicops-console-0.1.0-SNAPSHOT.jar app.jar

ENV JAVA_OPTS="-Xms256m -Xmx512m"
ENV SPRING_PROFILES_ACTIVE=prod

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
