package top.cywu.magicops.runtime.adapter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import top.cywu.magicops.http.model.HttpTarget;
import top.cywu.magicops.http.registry.HttpTargetRegistry;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * HttpTargetRegistry 从 http_targets 表同步测试（切片 33-c）。
 *
 * <p>覆盖关闭标准：Console 创建的 HTTP 目标在刷新周期内对 Runtime 生效。
 *
 * <p>生产拓扑下 http_targets 由 Console 经 Flyway 建表（共享 PostgreSQL）；
 * 本测试在 Runtime 独立 H2 上运行，故 @BeforeEach 按 V4 schema 建表。
 */
@SpringBootTest
class HttpTargetSyncTest {

    @Autowired
    private HttpTargetRegistry registry;

    @Autowired
    private HttpTargetSyncService syncService;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void createTable() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS http_targets ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "project_id BIGINT NOT NULL,"
                    + "target_id VARCHAR(100) NOT NULL,"
                    + "name VARCHAR(200) NOT NULL,"
                    + "base_url VARCHAR(1000) NOT NULL,"
                    + "allowed_paths TEXT,"
                    + "auth_type VARCHAR(50),"
                    + "auth_config_ref VARCHAR(200),"
                    + "require_encryption BOOLEAN NOT NULL DEFAULT FALSE,"
                    + "crypto_key_id VARCHAR(100),"
                    + "enabled BOOLEAN NOT NULL DEFAULT TRUE,"
                    + "created_at TIMESTAMP NOT NULL,"
                    + "updated_at TIMESTAMP NOT NULL)");
        }
    }

    @Test
    void httpTargetInDb_syncedToRegistry() throws Exception {
        String targetId = "sync-" + UUID.randomUUID();
        insertHttpTarget(targetId, "http://example.com/api", "/orders,/users", true);

        syncService.syncNow();

        assertTrue(registry.isRegistered(targetId), "DB 中的目标应同步到 Runtime 注册表");
        HttpTarget t = registry.getTarget(targetId).orElseThrow();
        assertEquals("http://example.com/api", t.baseUrl());
        assertTrue(t.isPathAllowed("/orders/123"));
    }

    @Test
    void disabledHttpTarget_notSynced() throws Exception {
        String targetId = "disabled-" + UUID.randomUUID();
        insertHttpTarget(targetId, "http://example.com/api", "/x", false);

        syncService.syncNow();

        assertFalse(registry.isRegistered(targetId), "disabled 目标不应同步");
    }

    /** 直接向 http_targets 插入一行，模拟 Console CRUD 写入。 */
    private void insertHttpTarget(String targetId, String baseUrl, String allowedPaths,
                                  boolean enabled) throws Exception {
        // project_id=1（测试库默认无外键约束；H2/PostgreSQL 兼容）
        try (Connection c = dataSource.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "INSERT INTO http_targets (project_id, target_id, name, base_url, "
                             + "allowed_paths, require_encryption, enabled, created_at, updated_at) "
                             + "VALUES (1, ?, ?, ?, ?, FALSE, ?, ?, ?)")) {
            ps.setString(1, targetId);
            ps.setString(2, "test-" + targetId);
            ps.setString(3, baseUrl);
            ps.setString(4, allowedPaths);
            ps.setBoolean(5, enabled);
            Timestamp now = Timestamp.from(Instant.now());
            ps.setTimestamp(6, now);
            ps.setTimestamp(7, now);
            ps.executeUpdate();
        }
    }
}
