-- 切片 33：Runtime 激活包持久化。
-- Runtime 重启后从此表重载激活包并重新验签，消除 AtomicReference 内存态（重启即丢）。
-- Console 经 Flyway 拥有生产 schema；Runtime 以 ddl-auto=validate 校验此表，开发态由 Hibernate 按实体建表。
CREATE TABLE active_packages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_version VARCHAR(100)    NOT NULL,
    environment     VARCHAR(50)     NOT NULL,
    key_id          VARCHAR(100)    NOT NULL,
    status          VARCHAR(30)     NOT NULL,
    payload         TEXT            NOT NULL,
    activated_at    TIMESTAMP       NOT NULL,
    activated_by    VARCHAR(100)
);

CREATE INDEX idx_active_packages_status ON active_packages(status);
