-- MagicOps 用户、角色和权限 schema
-- 切片 6：元数据持久化

-- 用户表
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    display_name    VARCHAR(200),
    email           VARCHAR(200),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    locked          BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL,
    last_login_at   TIMESTAMP
);

-- 角色表
CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)     NOT NULL UNIQUE,
    display_name    VARCHAR(200)    NOT NULL,
    description     VARCHAR(1000),
    created_at      TIMESTAMP       NOT NULL
);

-- 用户-角色关联表
CREATE TABLE user_roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL,
    role_id         BIGINT          NOT NULL,
    granted_at      TIMESTAMP       NOT NULL,
    granted_by      VARCHAR(100),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

-- 权限定义表
CREATE TABLE permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(100)    NOT NULL UNIQUE,
    display_name    VARCHAR(200)    NOT NULL,
    description     VARCHAR(1000),
    resource_type   VARCHAR(50),
    category        VARCHAR(50)
);

-- 角色-权限关联表
CREATE TABLE role_permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT          NOT NULL,
    permission_id   BIGINT          NOT NULL,
    granted_at      TIMESTAMP       NOT NULL,
    CONSTRAINT fk_role_perms_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_role_perms_perm FOREIGN KEY (permission_id) REFERENCES permissions(id),
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

-- 资源级权限表（用户/角色对特定资源的权限）
CREATE TABLE resource_permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    role_id         BIGINT,
    resource_type   VARCHAR(50)     NOT NULL,
    resource_id     VARCHAR(200)    NOT NULL,
    permission_code VARCHAR(100)    NOT NULL,
    granted_at      TIMESTAMP       NOT NULL,
    granted_by      VARCHAR(100),
    CONSTRAINT fk_res_perms_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_res_perms_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT chk_res_perms_owner CHECK (user_id IS NOT NULL OR role_id IS NOT NULL)
);

CREATE INDEX idx_user_roles_user ON user_roles(user_id);
CREATE INDEX idx_user_roles_role ON user_roles(role_id);
CREATE INDEX idx_role_perms_role ON role_permissions(role_id);
CREATE INDEX idx_res_perms_user ON resource_permissions(user_id);
CREATE INDEX idx_res_perms_role ON resource_permissions(role_id);
CREATE INDEX idx_res_perms_resource ON resource_permissions(resource_type, resource_id);

-- 预置角色
INSERT INTO roles (name, display_name, description, created_at) VALUES
    ('PLATFORM_ADMIN', '平台管理员', '用户、角色、系统配置、密钥配置和全局审计', CURRENT_TIMESTAMP),
    ('PROJECT_ADMIN', '项目管理员', '项目配置、环境配置、数据源配置和成员管理', CURRENT_TIMESTAMP),
    ('DEVELOPER', '开发人员', '草稿编辑、测试调试、提交审批', CURRENT_TIMESTAMP),
    ('APPROVER', '审批人员', '审核脚本、批准发布、批准高风险操作', CURRENT_TIMESTAMP),
    ('OPERATOR', '运维人员', '执行受控任务、查看日志', CURRENT_TIMESTAMP),
    ('AUDITOR', '安全审计员', '查看审计记录、导出报告、检查权限和发布记录', CURRENT_TIMESTAMP),
    ('OBSERVER', '只读观察者', '查看 API、日志和报告，无执行权限', CURRENT_TIMESTAMP);

-- 预置权限
INSERT INTO permissions (code, display_name, description, resource_type, category) VALUES
    ('script:create', '创建脚本', '创建新脚本草稿', 'project', 'script'),
    ('script:edit', '编辑脚本', '编辑脚本草稿内容', 'script', 'script'),
    ('script:debug', '调试脚本', '在受控环境调试脚本', 'script', 'script'),
    ('script:submit', '提交审批', '提交脚本版本进入审批流程', 'script', 'script'),
    ('script:approve', '审批脚本', '审批或拒绝脚本发布', 'script', 'script'),
    ('script:publish', '发布脚本', '构建签名并推送发布包', 'project', 'publish'),
    ('script:rollback', '回滚脚本', '回滚已发布的脚本版本', 'project', 'publish'),
    ('audit:read', '查看审计', '查看审计记录', 'global', 'audit'),
    ('audit:export', '导出审计', '导出审计报告', 'global', 'audit'),
    ('datasource:manage', '管理数据源', '注册和管理数据源配置', 'project', 'datasource'),
    ('datasource:query', '查询数据源', '在数据源上执行查询', 'datasource', 'datasource'),
    ('http_target:manage', '管理 HTTP 目标', '注册和管理 HTTP 目标系统', 'project', 'http'),
    ('key:manage', '管理密钥', '管理密钥引用和配置', 'global', 'crypto'),
    ('project:manage', '管理项目', '创建和管理项目配置', 'global', 'project'),
    ('user:manage', '管理用户', '创建用户和分配角色', 'global', 'admin'),
    ('role:manage', '管理角色', '修改角色和权限配置', 'global', 'admin'),
    ('system:config', '系统配置', '修改全局系统配置', 'global', 'admin');
