-- MagicOps 项目和环境 schema
-- 切片 6：元数据持久化

-- 项目表
CREATE TABLE projects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)     NOT NULL UNIQUE,
    name            VARCHAR(200)    NOT NULL,
    description     VARCHAR(2000),
    owner           VARCHAR(100),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL
);

-- 环境表（每个项目可有多个环境：development, staging, production）
CREATE TABLE environments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT          NOT NULL,
    name            VARCHAR(50)     NOT NULL,
    display_name    VARCHAR(200),
    environment_type VARCHAR(20)    NOT NULL,
    runtime_url     VARCHAR(500),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL,
    CONSTRAINT fk_env_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT uq_project_env UNIQUE (project_id, name)
);

-- 项目成员表
CREATE TABLE project_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT          NOT NULL,
    user_id         BIGINT          NOT NULL,
    role            VARCHAR(50)     NOT NULL,
    joined_at       TIMESTAMP       NOT NULL,
    CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_pm_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_project_member UNIQUE (project_id, user_id)
);

CREATE INDEX idx_environments_project ON environments(project_id);
CREATE INDEX idx_project_members_project ON project_members(project_id);
CREATE INDEX idx_project_members_user ON project_members(user_id);
