-- MagicOps 数据源和密钥引用 schema
-- 切片 6：元数据持久化

-- 数据源配置表
CREATE TABLE data_sources (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    display_name    VARCHAR(200),
    driver_class    VARCHAR(200)    NOT NULL,
    jdbc_url        VARCHAR(1000)   NOT NULL,
    username        VARCHAR(200),
    password_ref    VARCHAR(200),
    max_pool_size   INT             NOT NULL DEFAULT 5,
    read_only       BOOLEAN         NOT NULL DEFAULT FALSE,
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL,
    CONSTRAINT fk_ds_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT uq_project_ds UNIQUE (project_id, name)
);

-- 密钥引用表（脚本使用 keyId 引用，不直接使用原始密钥）
CREATE TABLE key_references (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id          VARCHAR(100)    NOT NULL UNIQUE,
    display_name    VARCHAR(200),
    algorithm       VARCHAR(50)     NOT NULL,
    key_type        VARCHAR(50)     NOT NULL,
    key_store_ref   VARCHAR(500),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    expires_at      TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL
);

-- HTTP 目标系统注册表
CREATE TABLE http_targets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT          NOT NULL,
    target_id       VARCHAR(100)    NOT NULL,
    name            VARCHAR(200)    NOT NULL,
    base_url        VARCHAR(1000)   NOT NULL,
    allowed_paths   TEXT,
    auth_type       VARCHAR(50),
    auth_config_ref VARCHAR(200),
    require_encryption BOOLEAN      NOT NULL DEFAULT FALSE,
    crypto_key_id   VARCHAR(100),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL,
    CONSTRAINT fk_ht_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT uq_project_target UNIQUE (project_id, target_id)
);

CREATE INDEX idx_data_sources_project ON data_sources(project_id);
CREATE INDEX idx_http_targets_project ON http_targets(project_id);
