-- MagicOps 发布包记录 schema
-- 切片 6：元数据持久化

-- 发布包记录表（记录每次发布的完整历史）
CREATE TABLE publish_packages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code    VARCHAR(50)     NOT NULL,
    environment     VARCHAR(50)     NOT NULL,
    package_version VARCHAR(20)     NOT NULL,
    runtime_version VARCHAR(20),
    published_by    VARCHAR(100)    NOT NULL,
    published_at    TIMESTAMP       NOT NULL,
    key_id          VARCHAR(100)    NOT NULL,
    sign_alg        VARCHAR(50)     NOT NULL,
    signature       TEXT            NOT NULL,
    metadata_hash   VARCHAR(64),
    policy_hash     VARCHAR(64),
    status          VARCHAR(30)     NOT NULL,
    runtime_response TEXT,
    created_at      TIMESTAMP       NOT NULL
);

-- 发布包-脚本关联表
CREATE TABLE publish_package_scripts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id      BIGINT          NOT NULL,
    script_id       VARCHAR(100)    NOT NULL,
    script_version  VARCHAR(20)     NOT NULL,
    path            VARCHAR(500)    NOT NULL,
    method          VARCHAR(10)     NOT NULL,
    scenario        VARCHAR(50),
    risk_level      VARCHAR(20),
    content_hash    VARCHAR(64),
    CONSTRAINT fk_pps_package FOREIGN KEY (package_id) REFERENCES publish_packages(id)
);

-- 发布包推送记录表
CREATE TABLE publish_push_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id      BIGINT          NOT NULL,
    runtime_url     VARCHAR(500)    NOT NULL,
    push_status     VARCHAR(30)     NOT NULL,
    http_status     INT,
    response_body   TEXT,
    pushed_at       TIMESTAMP       NOT NULL,
    duration_ms     BIGINT,
    CONSTRAINT fk_ppl_package FOREIGN KEY (package_id) REFERENCES publish_packages(id)
);

CREATE INDEX idx_publish_packages_project ON publish_packages(project_code);
CREATE INDEX idx_publish_packages_env ON publish_packages(environment);
CREATE INDEX idx_publish_packages_status ON publish_packages(status);
CREATE INDEX idx_publish_package_scripts_pkg ON publish_package_scripts(package_id);
CREATE INDEX idx_publish_push_logs_pkg ON publish_push_logs(package_id);

-- 注意：scripts.project_code 到 projects.code 的外键将在项目管理功能完成后添加（V7+）
-- 当前 project_code 作为自由文本使用，不强制引用 projects 表
