-- MagicOps 诊断中心 schema
-- 切片 20：Arthas 诊断中心核心实现

-- 诊断会话表
CREATE TABLE diagnosis_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_app      VARCHAR(200)    NOT NULL,
    target_host     VARCHAR(200)    NOT NULL,
    target_port     INT             NOT NULL,
    operator_id     BIGINT,
    status          VARCHAR(20)     NOT NULL,
    timeout_minutes INT             NOT NULL DEFAULT 30,
    created_at      TIMESTAMP       NOT NULL,
    closed_at       TIMESTAMP
);

-- 命令模板表
CREATE TABLE command_templates (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(200)    NOT NULL UNIQUE,
    command                 VARCHAR(2000)   NOT NULL,
    parameter_constraints   TEXT,
    risk_level              VARCHAR(20)     NOT NULL,
    requires_approval       BOOLEAN         NOT NULL DEFAULT FALSE,
    description             VARCHAR(2000),
    created_at              TIMESTAMP       NOT NULL,
    updated_at              TIMESTAMP       NOT NULL
);

-- 命令执行记录表
CREATE TABLE command_executions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT          NOT NULL,
    template_id         BIGINT,
    parameters          TEXT,
    resolved_command    VARCHAR(2000),
    output              TEXT,
    duration_ms         BIGINT,
    status              VARCHAR(20)     NOT NULL,
    executed_at         TIMESTAMP       NOT NULL,
    CONSTRAINT fk_cmd_exec_session FOREIGN KEY (session_id) REFERENCES diagnosis_sessions(id)
);

CREATE INDEX idx_diagnosis_sessions_status ON diagnosis_sessions(status);
CREATE INDEX idx_diagnosis_sessions_operator ON diagnosis_sessions(operator_id);
CREATE INDEX idx_command_executions_session ON command_executions(session_id);

-- 预置命令模板
INSERT INTO command_templates (name, command, risk_level, requires_approval, description, created_at, updated_at) VALUES
    ('dashboard', 'dashboard', 'LOW', FALSE, '实时系统面板', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('thread-top10', 'thread -n {count}', 'LOW', FALSE, '查看最忙的前N个线程', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('jvm', 'jvm', 'LOW', FALSE, 'JVM 信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sysprop', 'sysprop', 'LOW', FALSE, '系统属性', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('trace-method', 'trace {class} {method}', 'MEDIUM', FALSE, '方法调用链路追踪', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('watch-method', 'watch {class} {method} {params}', 'MEDIUM', FALSE, '观察方法调用参数', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('jad-decompile', 'jad {class}', 'HIGH', TRUE, '反编译类', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('sc-search', 'sc {pattern}', 'HIGH', TRUE, '搜索已加载类', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('retransform', 'retransform {path}', 'CRITICAL', TRUE, '重新加载类（高风险）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
