package top.cywu.magicops.runtime.datasource;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 数据源同步测试（切片 36）。
 *
 * <p>覆盖关闭标准：data_sources 表中 enabled 数据源同步到 DynamicDataSourceManager。
 */
@SpringBootTest(properties = "MAGICOPS_ENVIRONMENT=development")
class DataSourceSyncTest {

    @Autowired
    private DataSourceSyncService syncService;

    @Autowired
    private DynamicDataSourceManager dataSourceManager;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void createTable() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS data_sources ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "project_id BIGINT NOT NULL,"
                    + "name VARCHAR(100) NOT NULL,"
                    + "display_name VARCHAR(200),"
                    + "driver_class VARCHAR(200) NOT NULL,"
                    + "jdbc_url VARCHAR(1000) NOT NULL,"
                    + "username VARCHAR(200),"
                    + "password_ref VARCHAR(200),"
                    + "max_pool_size INT NOT NULL DEFAULT 5,"
                    + "read_only BOOLEAN NOT NULL DEFAULT FALSE,"
                    + "enabled BOOLEAN NOT NULL DEFAULT TRUE,"
                    + "created_at TIMESTAMP NOT NULL,"
                    + "updated_at TIMESTAMP NOT NULL)");
        }
    }

    @Test
    void enabledDataSource_syncedToManager() throws Exception {
        insertDataSource("business-his", "jdbc:h2:mem:his_test;DB_CLOSE_DELAY=-1", "env:HIS_DB_PASSWORD", true);
        System.setProperty("HIS_DB_PASSWORD", "his-secret");

        syncService.syncNow();

        // 注册后 getDataSource 不抛异常即说明已同步
        assertNotNull(dataSourceManager.getDataSource("business-his"));
        System.clearProperty("HIS_DB_PASSWORD");
    }

    @Test
    void disabledDataSource_notSynced() throws Exception {
        insertDataSource("disabled-ds", "jdbc:h2:mem:disabled_test", null, false);

        syncService.syncNow();

        assertThrows(IllegalArgumentException.class,
                () -> dataSourceManager.getDataSource("disabled-ds"),
                "disabled 数据源不应被同步");
    }

    @Test
    void emptyPasswordRef_registeredWithEmptyPassword() throws Exception {
        // 无密码的 H2 库（passwordRef 为空）应能注册
        insertDataSource("no-pw-ds", "jdbc:h2:mem:nopw_test;DB_CLOSE_DELAY=-1", null, true);

        syncService.syncNow();

        assertNotNull(dataSourceManager.getDataSource("no-pw-ds"));
    }

    private void insertDataSource(String name, String jdbcUrl, String passwordRef, boolean enabled) throws Exception {
        try (Connection c = dataSource.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "INSERT INTO data_sources (project_id, name, driver_class, jdbc_url, "
                             + "username, password_ref, max_pool_size, read_only, enabled, created_at, updated_at) "
                             + "VALUES (1, ?, 'org.h2.Driver', ?, 'sa', ?, 5, TRUE, ?, ?, ?)")) {
            ps.setString(1, name);
            ps.setString(2, jdbcUrl);
            ps.setString(3, passwordRef);
            ps.setBoolean(4, enabled);
            Timestamp now = Timestamp.from(Instant.now());
            ps.setTimestamp(5, now);
            ps.setTimestamp(6, now);
            ps.executeUpdate();
        }
    }
}
